name: Node.js CD

on:
  push:
    branches: [ "main" ]
jobs:
      deploy:
        runs-on: ubuntu-latest
        steps:
          - name: SSH Deploy
            run: |
              sshpass -p 123123 ssh -o StrictHostKeyChecking=no -p 19236 server1@$0.tcp.ap.ngrok.io
              cd /home/server1/project/test
              git pull origin main
              npm intall
              pm2 restart index
