name: Node.js CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no -p 19236 server1@$0.tcp.ap.ngrok.io << EOF
            cd /home/server1/project/test
            git pull origin main
            npm install
            pm2 restart index
          EOF
