name: Node.js CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy use ssh
      uses: appleboy/ssh-action@v1.0.3
      with:
        script: |
          sshpass -p 123123 ssh server1@0.tcp.ap.ngrok.io -p 19236
          cd project/test
          git pull origin main
          npm i
          pm2 restart index
    
